bf2fc6cc711aee1a0c2a/kas-fleetshard

operator/pom.xml
operator/src/main/java/org/bf2/operator/managers/StrimziBundleManager.java
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/MockResourceInformerFactory.java
operator/src/test/java/org/bf2/operator/managers/StrimziBundleManagerTest.java
pom.xml

The SBMTest failures were provoked by a changes to the MockResourceInformerFactory.  The factory was changed to produce informers that actually emit events - which I found useful elsewhere. This broke some assumptions made by the SBMTests.
The tests previously relied on testing business logic by calling methods exposed specifically for the unit test.  The code paths where the watcher actually called the business logic were untested making for a somewhat weak test.
The test is now refactored to use a simple watcher that mimics the important actions that would be made by OLM.  This
allows the code to be tested under conditions that match life much more closely.

Refactor StrimziBundleManager unit tests to avoid the need for 'test-only' methods.

---

operator/src/test/java/org/bf2/operator/managers/StrimziBundleManagerTest.java

I missed one in the big test refactor! This ought to have been part of #673.  It fails sporadically because the replacement of the packagemanifest may happen after the operator has already approved the valid one.
Signed-off-by: kwall <kwall@apache.org>

Refactor overlooked SBMTest.

---

operator/src/main/java/org/bf2/operator/managers/InformerManager.java
operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

Replacement for #666 
also increasing the memory request - based upon the observation of memory usage in production.
This switches the ingress logic from being node based to being demand based. There are pluses and minuses for doing it this way. The best plus is that it's more based upon actual need - that becomes more relevant as we need a greater number of ingress replicas per managed kafka (when the ingress/egress goes up). The other benefit is that you don't need to hard code what is the potential maximum load per node, instead you characterize what each ingress replica can handle and determine how many you need.
There are also 2 new properties that simply allow you to override how many replicas you actually want - that should be useful to kas-install and instance profiling.
The …

MGDSTRM-7464 switching the ingress sizing to be based on demand

---

operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaController.java
operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/Canary.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
operator/src/main/java/org/bf2/operator/operands/dev/DevelopmentKafkaCluster.java
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/strimzi.yml
perf/src/main/java/org/bf2/performance/AdopterProfile.java
perf/src/main/java/org/bf2/performance/InstanceProfiler.java
perf/src/main/java/org/bf2/performance/ManagedKafkaProvisioner.java
perf/src/test/java/org/bf2/performance/ManagedKafkaValueProdMinimumTest.java

This switches the fleetshard operator to using the partition count to drive the broker selection.
This requires adding a physical partition capacity value to the configuration to use as a reference.  I removed the old replicas value from the config, but it may be a good idea to add that back as an override to simply testing as noted in the ManagedKafkaProvisioner.
To support a single broker a subsequent pr will externalize the scalingAndReplicaionFactor - at worst it could be separate properties.
My understanding is that changing the broker count after the fact is not something that we don't want to do yet.  So similar to the consideration of not reducing volume sizes, to get the replica count we have to use both the managedkafka and the kafka, which makes these changes seem a bit messy. …

using partitions to drive the selection of the number of brokers

---

operator/src/main/resources/kafka-metrics.yaml

Changes to expose the new quota metrics made available by https://github.com/strimzi/kafka-quotas-plugin/pull/22 as prometheus metrics.
* `kafka_broker_quota_hardlimit` gives the quota storage hard-limit
* `kafka_broker_client_quota_limit{quota_type="(Produce|Fetch|Request)}` exposes the producer, fetch and request limits.
I also took the opportunity to the kafka_server_request_request_rate/kafka_server_request_throttle_time, as there omission 
seemed to be a gap.
Changes are backwardly compatible with the old plugin and existing alert rules etc.

Expose new quota plugin jmx metrics

---

operator/src/main/java/org/bf2/operator/managers/OperandOverrideManager.java
operator/src/main/java/org/bf2/operator/operands/AdminServer.java
operator/src/test/java/org/bf2/operator/operands/AdminServerTest.java
operator/src/test/resources/expected/adminserver-quarkus.yml
operator/src/test/resources/expected/adminserver-tls-quarkus.yml
operator/src/test/resources/expected/adminserver-tls.yml

Configure admin server health probes and exposed ports depending on whether property is present in ConfigMap with image reference. Obsolete code branches to be removed once new admin server is deployed to production.

Alter adminserver deployment depending on ConfigMap property (Quarkus)

---

operator/src/main/java/org/bf2/operator/managers/MetricsManager.java
operator/src/test/java/org/bf2/operator/managers/MetricsManagerTest.java

I noticed that sometimes after creating a managedkafka, the new metrics would show a NaN value, rather than the reflection of the kafka resource as expected.  It turns out there is a race. I misunderstood how `meterRegistry.gauge()` works, if the metric already exists (same name and tags), the method is a no-op.  This meant metric continued to return values from the initial kaka object and any updates were ignored.

Correct the handling of metric updates.

---

perf/scripts/osd-provision.sh

Added a default value to the `RESULTS_DIR` variable to be able to attach the log to the artifacts into the jenkins pipelines
https://issues.redhat.com/browse/MGDSTRM-7843

Fix RESULTS_DIR variable when a cluster provision fails

---

systemtest/src/test/java/org/bf2/systemtest/integration/ManagedKafkaST.java

Because this functionality/behavior is daily tested in scope of strimzi tests we really do not need to test in fleetshard operator tests.

Remove strimzi duplicated tests

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java

We don't have to put a lot of effort into this because it's primarily due to the service watch issue.  It's still possible as a timing issue, but that would be exceedingly rare.  Since an empty string was already being returned, just added that here.

MGDSTRM-7845 removing the possibility of the service npe

---

operator/src/main/java/org/bf2/operator/operands/AdminServer.java
operator/src/test/java/org/bf2/operator/operands/AdminServerTest.java

Include URI scheme (http/https) reported in the `adminServerURI` of the MK status.
MGDSTRM-7766

Add scheme to `adminServerURI` in ManagedKafka status

---

sync/src/main/resources/application.properties

Allows sync to run (without crash-loops) in environments without external SSO or configuration secret being available.
With this change, the value of env `SSO_ENABLED` must be set to `true` to re-enable the functionality turned off by default.

Configure default sync properties for standalone deployment

---

operator/src/main/java/org/bf2/operator/managers/OperandOverrideManager.java
operator/src/main/java/org/bf2/operator/managers/StrimziManager.java
operator/src/test/java/org/bf2/operator/managers/StrimziManagerTest.java

With this change, the fleetshard operator will support specifying canary, canary-init, admin-server, and Kafka images in annotations on the Strimzi deployment's pod template.
```yaml
managedkafka.bf2.org/kafka-images: |
2.8.1=quay.io/mk-ci-cd/kafka-28@sha256:cd9d97704f5a729154f82acf06eabb25b9cff985423c9ffbccaefd35b6858953
3.0.0=quay.io/mk-ci-cd/kafka-30@sha256:49b743b887318d2e5c74f99e864d6f646dabc000d9c093a500916bcee1a7cf10
managedkafka.bf2.org/related-images: |
{
"canary-init": "quay.io/mk-ci-cd/strimzi-canary@sha256:1ad0e8aaad71b5fc230ce12359d0fafeec2361948501234962346c0e4492d9d0",
"canary": "quay.io/mk-ci-cd/strimzi-canary@sha256:1ad0e8aaad71b5fc230ce12359d0fafeec2361948501234962346c0e4492d9d0",
"admin-server": "quay.io/mk-ci-cd/kafka-admin-api@sha256:f55f80fdfca47152d0991881998cdcc1308 …
```

Retrieval of Kafka, Canary, and Admin server images from annotations

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
operator/src/main/resources/instances/managedkafka.properties
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/strimzi.yml

Previously the code assumed that the PV capacity's was the same same as the available space on the volume provisioned by OpenShift CSI.  This fails to account for the formatting overhead.
The service currently relies on the default `storageclass`, which uses a default `fsType`, which defaults to `ext4`. 
Actually calculating the exact formatting overhead for ext4 is non-trivial.  Instead we use a 5% heuristic which is shown to be sufficient for storage sizes of 16Ti and below (the ext4 maximum).  Note that volumes are formatted with the `reserved for root` disabled, so we don't need to consider that.
When this code is deployed, any existing kafka instances will have their storage increased by 5%.
There's more discussion on https://issues.redhat.com/browse/MGDSTRM-8072

bugfix: compensate for the ext4 formatting overhead in storage calculations

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java

This adds:
* a delay - since we observe events firing rapidly together from the deployment, before our edit has taken effect (there will be upstream changes that help introduce an application level cache that can prevent this in most circumstances in the future)
* a check if the edit is needed - I have not reproduced the situation or observed directly the cause, but it's possible that even what we think is an empty edit/patch could still be updating the resource, so we should check before hand if it really needs updated.

MGDSTRM-7790 adding a delay to modifying the ingress deployment

---

operator/src/main/java/org/bf2/operator/managers/ImagePullSecretManager.java
operator/src/main/java/org/bf2/operator/managers/SecuritySecretManager.java

MGDSTRM-8214
Also includes an option to specify image pull secret names, useful for development when the operator is not running as a Kubernetes deployment.

Calculate secret digest using data values to prevent spurious updates

---

.github/project.yml

This PR also goes back to having the `main` POM versions be set to the next SNAPSHOT release (see #230), as set by `next-version` for each release.
@rareddy , @shawkins - we can also leave `next-version` set to `999-SNAPSHOT`, let me know your thoughts.

Release 0.22.0

---

sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java

The operator sdk will not process events if the finalizer is removed (which seems like an sdk bug, which will no longer apply to us after https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/pull/708/commits/e7f77ab96da923d068ef4e12edeee585dd1c6403)
So changing the metadata copying to be just labels and annotations.
Also this could have been avoided with fabric8 apply support - however even basic server side apply support is not coming until 6.0.

copying only the labels and annotations

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

Prior to issuing a patch we'll use the diff logic to determine if the patch is even needed.  Simply having fields added in existing state is just a side effect of the ingress controller operator - with the worst case is that the application of our patch then causes another update, which can repeat for quite a while.
So we need to see something removed or modified to submit the patch.  
I only see two updates being clustered by the operator in my local testing, so I didn't bother adding a time delay like with the ingress replicas.
This strategy could be employed for any dependent resource that we are attempting to patch that is modified by their respective controller / operator.

MGDSTRM-8409 cut down on modifications to the ingresscontroller

---

operator/src/main/resources/kafka-metrics.yaml

What I'm thinking for the alerts is something like the following:
```yaml
expr: kafka_producer_metrics_outgoing_byte_rate < 10 or on(something) kafka_producer_metrics_connection_count = 0
for: 5m
```

Expose some client metrics for quota plugin alerts

---

operator/pom.xml
pom.xml
sync/pom.xml

- removed quarkus-junit5 from modules that don't require it
- refactor to allow overriding of: quarkus-junit5, jakarta.validation, openshift-model-common

Cleanup dependencies

---

sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
sync/src/main/java/org/bf2/sync/SecretManager.java
sync/src/test/java/org/bf2/sync/PollerTest.java

Small fix to the secret manager to update secret-digest and tests for the annotation of the `master-secret`

Adding test for annotation

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
operator/src/main/resources/application.properties
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/scaling-one.yml
operator/src/test/resources/expected/strimzi.yml

In the broker plugins project, we're updating the config properties so that they don't have the strimzi prefix.
This change updates the config set by this operator so that both the old and new properties are set. Once the version of the operator using the new properties is rolled out, we can then remove the old properties from being set here again in another change.
Given that this is intended to be a temporary duplication, I tried to keep it as simple as possible, so that it will be simple to remove when we get to that stage also.

Use new prefix for broker plugins properties

---

perf/scripts/osd-provision.sh

This gives the user option to specify `--addon-json-config` when installing the addon. In case the config is not provided - the old approach using templates is followed.
This is useful e.g. for `connectors-operator` we test - this addon requires several parameters to be specified, so the predefined template is something we can't use.

Add option for specifying the addon json when installing addon

---

operator/src/main/java/org/bf2/operator/managers/SecuritySecretManager.java
operator/src/test/java/org/bf2/operator/managers/SecuritySecretManagerTest.java
sync/src/main/java/org/bf2/sync/SecretManager.java

Also:
- (sync) Check for presence of MK Oauth clientId/secret before adding to master-secret (NPE avoidance)
- (operator) update tests to encode secret values
- (operator) do not assume secret references point to master-secret

[MGDSTRM-8716] Decode values when reading from master-secret

---

perf/scripts/osd-provision.sh

Fixing this issue https://issues.redhat.com/browse/MGDSTRM-8836
When we want to use an already created cluster for developing purposes, we get an error every time there is no quota available to create a new one because it is trying to do that. 
Checking first if it already exists is better than trying and wait for the error.

Fixed error when no quota is available and wanted to reuse an already installed cluster

---

api/src/main/java/org/bf2/operator/resources/v1alpha1/ServiceAccount.java
common/src/main/java/org/bf2/common/OperandUtils.java
operator/src/main/java/org/bf2/operator/managers/SecuritySecretManager.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstance.java
operator/src/test/java/org/bf2/operator/operands/KafkaInstanceTest.java
sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
sync/src/main/java/org/bf2/sync/SecretManager.java

Also adds some debug logging in sync around the changes received from the control plane.

[MGDSTRM-8959] Delay KafkaInstance reconcile until master secret created

---

ADVANCED.md
operator/src/main/java/org/bf2/operator/managers/OperandOverrideManager.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
operator/src/test/resources/expected/custom-config-strimzi.yml

Using this mechanism, we can override configuration passed to the broker by populating the `brokerConfig` object on the operator override.  This will have utility for temporary feature flags as well as experimentation in dev.    Note you can remove a broker config key by passing a null value.
```
oc edit cm -n redhat-managed-kafka-operator  strimzi-cluster-operator.v0.26.0-15
```
```
fleetshard_operands.yaml: |
canary:
init:
image: null
admin-server:
image: null
kafka:
brokerConfig:
kas.policy.topic-config.topic-config-policy-enforced: "true" # Inject a new broker config item
auto.create.topics.enable: ~ # Null causes an existing one to be removed.
```
and showing it works end to end:
```
% oc logs -f kafka-instance-kafka-0 | grep kas.policy.topic-config.topic-config-policy-enforced …
```

MGDSTRM-9050: expose generic mechanism for injecting additional broker configuration from the operand override

---

operator/src/main/java/org/bf2/operator/operands/Canary.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/operands/CanaryTest.java

- Conditionally use TLS certificate from MK CR when available, else use the Strimzi CA certificate (current behavior)
- Remove obsolete canary option to use non-existent internal port 9093 (MGDSTRM-9118)

[MGDSTRM-9117] Canary support provided TLS trusted certificate

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

This change aims to work around issues on the ingress/egress metrics emitted by the service.
It was discovered that the data transfer metrics (which is exposed to the service user via the console and fleetmanager metrics endpoint) is being reported incorrectly.  In short, this is due to the fact that haproxy [counters used for statistics calculation are incremented only when a session finishes](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#4.2-option%20contstats) coupled with the way haproxy is reconfigured with new configuration means in progress ingress and egress metrics for inflight connections are lost every time there is a provision or deprovision kafka instance event on the dataplane. For applications like kafka where connections are long lived, this can result in a …

haproxy: allow configuration of hard-stop-after configuration and contstats.

---

operator/src/main/java/org/bf2/operator/managers/StrimziClusterRoleBindingManager.java
operator/src/main/kubernetes/kubernetes.yml
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/managers/StrimziClusterRoleBindingManagerTest.java

Remove Strimzi cluster role bindings when the subject is in a nonexistent namespace.

[MGDSTRM-7353] Remove Strimzi cluster role bindings w/o namespace match

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java

prevents periodic, believed harmless, messages in the fleetshard logs
```
Updating the existing IngressController openshift-ingress-operator/kas [{"op":"replace","path":"/spec/unsupportedConfigOverrides/reloadInterval","value":60}]
```

fix: spec/unsupportedConfigOverrides/reloadInterval backing var has wrong type

---

perf/scripts/osd-provision.sh
perf/templates/CCS_DEFINITION.template

[MGDSTRM-8938](https://issues.redhat.com/browse/MGDSTRM-8938)
Update the `osd-provision.sh` script to allow GCP clusters to be provisioned. The script contains sample commands on how to create a GCP cluster. A GCP service account is required. The script will default to `--cloud-provider aws`,  so it shouldn't break any existing CI.

Add GCP cluster support to OSD provision script

---

api/src/main/java/org/bf2/operator/resources/v1alpha1/ManagedKafka.java
operator/src/main/java/org/bf2/operator/operands/AdminServer.java
operator/src/main/java/org/bf2/operator/operands/Canary.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstance.java
operator/src/main/java/org/bf2/operator/operands/ReservedDeploymentConverter.java
operator/src/main/kubernetes/kubernetes.yml
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
operator/src/test/resources/expected/reserved.yml
perf/src/main/java/org/bf2/performance/InstanceProfiler.java
perf/src/main/java/org/bf2/performance/ManagedKafkaProvisioner.java
sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
sync/src/test/java/org/bf2/sync/PollerTest.java

Updating the pr to be independent of capacity reporting.  If the operator sees a deployment marked as reserved, then it won't actually create the expected resources.  Instead deployments with pause pods at a lower priority will be created with resources and replicas that match the expected instances.  The parent managedkafka will be marked as ready once all of these deployments are ready.
The priority class kas-fleetshard-reservation (which I'm open to changing) was added to the kubernetes.yml in the project as we need it to be part of the workload, which diverges from the kas-fleetshard-high used in the bundle for the operator components.
There is no interaction with metrics as those are derived from kafka resources.
This change has no expectation that profile specific machine pools will …

MGDSTRM-8585 adding support for reserved deployments

---

operator/src/main/resources/instances/developer.properties
operator/src/test/resources/expected/developer-strimzi.yml

For now the capacity values are technically optional, so we should have valid defaults - however the control plane is supplying these, so there should be no impact to actual instances.  Once we address https://issues.redhat.com/browse/MGDSTRM-8648 we could remove the possibility of not setting these capacity values.

MGDSTRM-9334 correcting the defaults for developer instances

---

operator/src/main/resources/application.properties
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/strimzi.yml
operator/src/test/resources/expected/strimzi_su2.yml

This is causing a regression when creating topics using the RHOAS CLI:
```
rhoas kafka topic create --name=foo2 -v
{"id":"8","kind":"Error","href":"/api/v1/errors/8","reason":"Request violates topic configuration policy","code":400,"error_message":"Request violates topic configuration policy"}%
```

MGDSTRM-9425: retention.ms missing from managedkafka.kafka.topic-config-mutable-rule config

---

operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaAgentController.java
operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaController.java
operator/src/main/java/org/bf2/operator/events/ControllerEventFilter.java
operator/src/main/java/org/bf2/operator/managers/MetricsManager.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstance.java
operator/src/test/java/org/bf2/operator/events/ControllerEventFilterTest.java
operator/src/test/java/org/bf2/operator/operands/KafkaInstanceTest.java
pom.xml

- Pause ManagedKafka reconciliation based on annotation `managedkafka.bf2.org/pause-reconciliation=true`
- Update quarkus-operatork-sdk to 3.0.9 + implement event filter to process events for modified generation or changes to labels/annotations

[MGDSTRM-9354] Pause ManagedKafka reconciliation based on annotation

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
operator/src/main/resources/application.properties
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/scaling-one.yml
operator/src/test/resources/expected/strimzi.yml
operator/src/test/resources/expected/strimzi_su2.yml

The broker plugin was refactored to us avoid use of 'strimzi' in its configuration properties.  The version of the plugin that replied on the old name is no longer in use.  Thus the configuration using the old name can now be removed.

remove now redundant broker plugins properties

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

also simplifying the logic based upon the possibility of dynamic scaling and node balancing - since we are enforcing balanced node scaling and have the topology spread constraint / scaling factor on brokers, we shouldn't need any deep node logic here.

MGDSTRM-9567 MGDSTRM-9555 allowing for the transition from 3 to 2

---

operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaController.java
operator/src/main/java/org/bf2/operator/operands/AbstractAdminServer.java
operator/src/main/java/org/bf2/operator/operands/AbstractCanary.java
operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/AdminServer.java
operator/src/main/java/org/bf2/operator/operands/Canary.java
operator/src/main/java/org/bf2/operator/operands/DeploymentOperand.java
operator/src/test/java/org/bf2/operator/operands/AdminServerTest.java
operator/src/test/java/org/bf2/operator/operands/CanaryTest.java
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java

Given that node auto-scaling can introduce a delay in the deployment of the kafka, it would be best to wait until it is ready before creating the other deployments, so that any applicable timeouts start only at that point.  
The only difference to this approach vs now is there will be a small delay in the instance being seen as ready, and if the kafka ends up in an error state that will be reported as Ready=False Reason=Installing - because the admin / canary will still be in the installing state. Given the direction of MGDSTRM-9395 / MGDSTRM-9498 that is probably ok - the fleetmanager doesn't want to show the installation in an failed state regardless until the slo has expired.  However it hasn't been, and still won't be, clear the difference between installing and error - so we may …

MGDSTRM-9483 delaying deployment of admin/canary until kafka is ready

---

operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/strimzi.yml
operator/src/test/resources/expected/strimzi_su2.yml
pom.xml

Note that new property `createBootstrapService` is present with default value `true`. This property only applies to the load balancer listener type (not ingress/route types) - see [1] for more info.
[1] https://github.com/strimzi/strimzi-kafka-operator/pull/6170

[MGDSTRM-9509] Bump Strimzi API version from 0.26.0 to 0.29.0

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/test/resources/expected/developer-strimzi.yml

PodSet pods won't have a parent deployment.  This annotation will allow them to still be movable by the auto-scaler.  This does not yet address a non-developer bin-packing scenario as we're not sure if that will be needed.

MGDSTRM-9508 making sure the developer instances are movable

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/test/resources/expected/reserved-cruisecontrol.yml
operator/src/test/resources/expected/reserved.yml

I was mistaken that this could be addressed by using a patch - the selectors are still immutable.  The proper way to do this is to just choose labels that won't change, similar to what is applied to our other deployments.

MGDSTRM-9666 removing labels that may change from reserved selectors

---

operator/src/main/resources/kafka-logging.yaml

Why:
We are syncing our log levels with upstream kafka defaults. The default for this logger changed here: https://github.com/apache/kafka/commit/c59835c1d7281863722f5c11b54e6b9c07070304
MGDSTRM-9284

MGDSTRM-9284: Change broker log configuration to sync with upstream kafka and remove unused config

---

operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfigurations.java
operator/src/main/resources/instances/standard-dynamic.properties
operator/src/test/java/org/bf2/operator/operands/KafkaInstanceConfigurationsTest.java
operator/src/test/resources/expected/adminserver-affinity.yml

We don't have a great mechanism for this - it's dependent upon both profile type and strimzi version.  So for now I'm just creating a one-off that we can refine later.
I've also refined the initially proposed values slightly so that the cpu request of the broker will fit on an r5.xlarge that has a max allocatable cpu of 3.5.  The cpu limit was then raised separately, so the numbers will still be inline with what was reported.

MGDSTRM-9799 adding overrides for standard / r5.xlarge

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/dev/DevelopmentKafkaCluster.java
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/scaling-one.yml
operator/src/test/resources/expected/strimzi.yml
operator/src/test/resources/expected/strimzi_su2.yml

Why:
If a client uses incorrect credentials, or there is some other problem with authentication this will reduce pressure on any backing authentication services.

Increase connection.failed.authentication.delay.ms to 1000

---

operator/src/main/java/org/bf2/operator/managers/OperandOverrideManager.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/kubernetes/kubernetes.yml
operator/src/main/resources/instances/standard-dynamic.properties
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
operator/src/test/java/org/bf2/operator/operands/KafkaInstanceConfigurationsTest.java
perf/src/main/java/org/bf2/performance/InstanceProfiler.java
perf/src/main/java/org/bf2/performance/ManagedKafkaProvisioner.java

also adding some trivial instance profiler changes.

MGDSTRM-10039 elevating the priority of broker and zookeeper pods

---

operator/src/main/java/org/bf2/operator/managers/StrimziBundleManager.java
operator/src/main/kubernetes/kubernetes.yml
operator/src/test/java/org/bf2/operator/managers/StrimziBundleManagerTest.java

Changes the Strimzi bundle subscription's install plan approval to `Manual` when not already set. 
This may be tested with kas-installer and the branch in https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/1387 (until accepted/merged). 
Current state of KFM in standalone mode will deploy Strimzi with the Automatic install plan approval and without the necessary labels for FSO to find the subscription. The KFM PR adds the labels to match the addon installation method.

[MGDSTRM-10052] Set Strimzi bundle install plan to Manual

---

operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

Based upon some additional scale testing I'm seeing no worse than 100MiB per 10000 connections, so we should be good to lower our memory request to 1 gig instead of 2.  We should also try to satisfy the connection demand for ~36 SU to match our current assumptions about bandwidth at a rate of 100% peak (locally I actually had to set the max connections well above the desired level to not see any errors - so even the 100% rate could be conservative).

MGDSTRM-10069 updating the properties based upon additional testing

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerWithProfilesTest.java

also addressing a bug that will keep adding the toleration to the ingresscontroller

MGDSTRM-10130 addressing test inconsistency

---

common/src/main/java/org/bf2/common/health/SystemTerminator.java
sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
sync/src/test/java/org/bf2/sync/PollerTest.java

This is purely trying to be more defensive to what was seen in MGDSTRM-10277.  However there remains a completely unknown root cause - I didn't see anything exceptional called out.  It's also not clear why only sync would be affected - we've moved up enough in the operator sdk such that it's using an informer for the primary controller resource (managedkafka) that should be exactly the same as what the sync is running.

MGDSTRM-10277 hardening the sync against unhealthy behavior

---

api/src/main/java/org/bf2/operator/resources/v1alpha1/NetworkConfiguration.java
operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

Adds a new stanza to the agent spec to control the scope of the ic NLBs.
Since we have a timed job for reconciliation, we don't need to add a specific event handler for the managedkafkaagent - an assumption we were already making about the profile logic.

MGDSTRM-10232 initial configuration to control the ic scope

---

common/src/main/java/org/bf2/common/OperandUtils.java
operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/AdminServer.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/kubernetes/kubernetes.yml
operator/src/main/resources/application.properties
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

Enables the (unsupported) dynamic config manager option on openshift-ingress.  This is done as otherwise, haproxy reconfigurations (which occur every time new kafka instance is provisioned or deprovisioned) cause all kafka connections to all instances to be dropped.  This is too disruptive for applications.
Work based on ideas from @shawkins and @showuon .

MGDSTRM-9181: Have kas ingress controller utilise the openshift-router's dynamic config manager.

---

operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/resources/application.properties

#850 was incomplete as we failed to consider suspended routes, so instance suspension was still leading to a haproxy restart.  This creates blueprints for those routes too.

bug fix: create blueprints for suspended routes too

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/resources/application.properties
sync/src/main/java/org/bf2/sync/ManagedKafkaAgentSync.java
sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
sync/src/main/java/org/bf2/sync/controlplane/MockControlPlane.java
sync/src/main/java/org/bf2/sync/informer/InformerManager.java
sync/src/main/resources/application.properties
systemtest/src/main/java/org/bf2/systemtest/api/sync/SyncApiClient.java
systemtest/src/main/java/org/bf2/systemtest/framework/SecurityUtils.java
systemtest/src/main/java/org/bf2/systemtest/framework/TestPlanExecutionListener.java
systemtest/src/main/java/org/bf2/systemtest/operator/FleetShardOperatorManager.java
systemtest/src/main/java/org/bf2/systemtest/operator/KeycloakOperatorManager.java
systemtest/src/test/java/org/bf2/systemtest/integration/AbstractST.java
systemtest/src/test/java/org/bf2/systemtest/integration/ManagedKafkaST.java
systemtest/src/test/java/org/bf2/systemtest/integration/SmokeST.java
systemtest/src/test/java/org/bf2/systemtest/integration/UpgradeST.java
systemtest/src/test/java/org/bf2/systemtest/unit/SuiteUnitTest.java
test/src/main/java/org/bf2/test/TestUtils.java

- Add test for MGDSTRM-9790 to suspend, upgrade Strimzi, and resume an MK
- Increase operator reconcile max retry attempts, used when unhandled exceptions occur
- Delay sync's polling of mock control plane in test profile (account for observed HTTP server startup time)
- Modify sync's MK agent informer to only watch own namespace (aligns with `ManagedKafkaAgentSync` processing)
- Deploy Keycloak and kas-fleetshard only once per suite execution

[MGDSTRM-9790] Test instance upgrade while suspended

---

operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java

We need to leave the unsupport option as an int, but change the tuning option to a string.

MGDSTRM-10459 changing the reloadInterval tuning option to a string

---

operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
operator/src/main/resources/instances/managedkafka.properties
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/scaling-one.yml
operator/src/test/resources/expected/strimzi.yml
operator/src/test/resources/expected/strimzi_su2.yml

This is a DoS defence.  This change bakes the configuration into fleetshard, allowing the override to be removed from the overrides.

MGDSTRM-10104: configure kafka with smaller sasl.server.max.receive.size

---

operator/src/main/java/org/bf2/operator/managers/StrimziManager.java
operator/src/main/kubernetes/kubernetes.yml
operator/src/test/java/org/bf2/operator/MockResourceInformerFactory.java
operator/src/test/java/org/bf2/operator/managers/StrimziManagerTest.java

Why:
As part of enabling StrimziPodSets in the cluster operator we are also increasing availability of the operator by running 2 replicas and using a k8s lease to elect one of them as a leader, the other will be in standby in case it needs to take over reconciliation. The lease is not able to be automatically cleaned up when we tear down a cluster operator deployment, so we are making the Fleetshard Operator responsible for deleting the lease in reaction to a deployment deletion.
This is the upstream issue in the fabric8 client https://github.com/fabric8io/kubernetes-client/issues/4638, once this is resolved we can remove this work from Fleetshard and configure an owner reference in the Strimzi cluster operator
Note that the lease is named ${deploymentName}-leadership-token by convention …

MGDSTRM-10325: Delete Strimzi cluster operator leadership lease on deployment deletion

---

.github/workflows/publish.yml
api/pom.xml
common/pom.xml
operator/pom.xml
perf/pom.xml
pom.xml
sync/pom.xml
systemtest/pom.xml
test/pom.xml

- Add workflow to publish artifacts on pushes to `main` (snapshot versions) and for each release (regular/non-snapshot versions)
- Add `kas-fleetshard-` prefix to the `systemtest` and `test` artifact ids to avoid potential conflicts elsewhere in bf2
- Update version to 0.33.0-SNAPSHOT to reflect the plan for `main`
The packages were published [1] from the first commit by having the PR's source branch named in the action YAML. The second commit removes the branch going forward.
[1] https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/actions/runs/4008001312

[MGDSTRM-10349] Publish kas-fleetshard artifacts to GitHub packages

---

operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/test/resources/expected/custom-config-strimzi.yml
operator/src/test/resources/expected/developer-strimzi.yml
operator/src/test/resources/expected/strimzi.yml
operator/src/test/resources/expected/strimzi_su2.yml

Test OLM index image with this change: `quay.io/medgar/kas-fleetshard-operator-index:1.0.17-1`

[MGDSTRM-10669] Allow access via 9096 for any Kafka pod in namespace

---

bundle/pom.xml
bundle/src/main/sh/build-push-index.sh

Allows the bundle image to be referenced via SHA rather than tag by the index
Relates to MGDSTRM-10595

Use OLM bundle image digest file to pin image used by index

---

.github/workflows/auto-labeler.yaml
.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
.github/workflows/smoke.yaml
.github/workflows/sonar.yml
.github/workflows/test.yaml

Updating various action versions.  Moving caching to the setup-java action.  Having everything use temurin - previously zulu (the default), adopt, and temurin were referenced.  Not sure if we have a hard preference here.

MGDSTRM-10828 updating github actions

---

common/src/main/java/org/bf2/common/OperandUtils.java
operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaController.java
operator/src/main/java/org/bf2/operator/managers/KafkaManager.java
operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
operator/src/test/java/org/bf2/operator/controllers/ManagedKafkaControllerTest.java
operator/src/test/java/org/bf2/operator/managers/KafkaManagerTest.java
operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java

This moves the upgrade annotations from the managedkafka to kafka.  After this version is rolled out, we'll be able to remove the logic in the controller that is checking for moving the annotations and remove the annotations from the list of ones that are managed by the operator.

MGDSTRM-10094 making KafkaCluster.fromKafka not modify the ManagedKafka

---

operator/src/main/java/org/bf2/operator/managers/CapacityManager.java
operator/src/test/java/org/bf2/operator/managers/CapacityManagerTest.java

With later josdk we'll likely enable leader election.

MGDSTRM-10985 accounting for the possibility of competing operators

---

operator/src/main/java/org/bf2/operator/managers/StrimziBundleManager.java
operator/src/test/java/org/bf2/operator/managers/StrimziBundleManagerTest.java

In addition to the case when the CRDs are not present, also approve Strimzi installation immediately when the subscription does not have a linked CSV yet. This likely only applies to test environments where the operator is installed/removed repeatedly and the CRDs are kept in the cluster.

Approve Strimzi installation immediately when CSV not present
