bf2fc6cc711aee1a0c2a/kas-fleetshard

- operator/src/test/resources/expected/adminserver-quarkus.yml
- operator/src/test/resources/expected/adminserver-tls-quarkus.yml
- operator/src/test/resources/expected/adminserver-tls.yml
- operator/src/test/resources/expected/scaling-one.yml
New tests added in #680 were not accounted for in #678 and #676
> Fix unit test expectations

- operator/src/main/java/org/bf2/operator/managers/OperandOverrideManager.java
- operator/src/main/java/org/bf2/operator/managers/StrimziManager.java
Noticed while updating the rhosak-index for https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/146
MGDSTRM-7846
> Correct several log format place-holders

- operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
- operator/src/main/resources/application.properties
also removing a comment that is no longer applicable
> upping the memory request to match production load

- api/src/main/java/org/bf2/operator/resources/v1alpha1/ManagedKafkaAuthenticationOAuth.java
- operator/src/main/java/org/bf2/operator/managers/SecuritySecretManager.java
- operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
- operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
> Make OAuth clientId and clientSecret optional

- .github/project.yml
Signed-off-by: Ramesh Reddy <rareddy@jboss.org>
> Update project.yml for next release of FSO 0.21.0

- .github/workflows/release.yml
> Configure CI bot email for release commits

- .github/project.yml
> Release 0.22.1

- perf/scripts/update_env.sh
> fix #660: removing set -e as that causes the shell to later terminate

- operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
- operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
- operator/src/main/resources/instances/managedkafka.properties
- operator/src/test/resources/expected/custom-config-strimzi.yml
- operator/src/test/resources/expected/developer-strimzi.yml
- operator/src/test/resources/expected/scaling-one.yml
- operator/src/test/resources/expected/strimzi.yml
JIRA: https://issues.redhat.com/browse/MGDSTRM-8361
> Add config to enable partition limit enforcement

- operator/src/main/java/org/bf2/operator/managers/ImagePullSecretManager.java
- operator/src/test/java/org/bf2/operator/managers/ImagePullSecretManagerTest.java
> Delete pull secret before create when type has changed

- operator/src/main/resources/kafka-metrics.yaml
Part of [MGDSTRM-8172](https://issues.redhat.com/browse/MGDSTRM-8172) to expose broker state to CS-SRE & CEE.
> Add kafka_broker_state as an exported metric

- api/src/main/java/org/bf2/operator/resources/v1alpha1/Versions.java
- operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
- operator/src/main/java/org/bf2/operator/operands/KafkaInstanceConfiguration.java
- operator/src/main/resources/cruise-control-logging.yaml
- operator/src/main/resources/instances/developer.properties
- operator/src/main/resources/instances/managedkafka.properties
- operator/src/main/resources/instances/standard.properties
- operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
- operator/src/test/resources/expected/strimzi.yml
- operator/src/test/resources/expected/strimzi_su2.yml
- operator/src/test/resources/expected/strimzi_su2_cc.yml
Enables Cruise Control support.
> Cruisecontrol integration

- .github/project.yml
> Create 0.24.0 release

- operator/src/main/java/org/bf2/operator/managers/SecuritySecretManager.java
- operator/src/test/java/org/bf2/operator/managers/SecuritySecretManagerTest.java
Fix null check when mapping OAuth/SSO trusted certificate
> [MGDSTRM-8940] Fix null check when mapping OAuth/SSO trusted certificate

- .github/project.yml
> Release 0.24.2

- .github/project.yml
> creating Release 0.24.3

- ADVANCED.md
Add Cruise Control logging level instructions to ADVANCED.md
Signed-off-by: Katherine Stanley <11195226+katheris@users.noreply.github.com>
> feat: Add Cruise Control logging level instructions

- operator/src/main/java/org/bf2/operator/operands/KafkaCluster.java
- operator/src/main/resources/cruise-control-metrics.yaml
- operator/src/test/resources/expected/strimzi_su2.yml
Adding cruise control metrics JMX config.
JIRA: MGDSTRM-8819
TODO:
> Add cruise control metrics config

- .github/project.yml
Signed-off-by: Ramesh Reddy <rareddy@jboss.org>
> FSO release 0.25.0

- operator/src/main/resources/instances/managedkafka.properties
- operator/src/test/resources/expected/custom-config-strimzi.yml
- operator/src/test/resources/expected/developer-strimzi.yml
- operator/src/test/resources/expected/scaling-one.yml
- operator/src/test/resources/expected/strimzi.yml
- operator/src/test/resources/expected/strimzi_su2.yml
Setting the kafka.partition-limit-enforced property to true for work on [MGDSTRM-8672](https://issues.redhat.com/browse/MGDSTRM-8672)
> Set kafka.partition-limit-enforced to true

- pom.xml
> bump quarkus version from 2.7.5 to 2.7.6

- ADVANCED.md
I noticed the instructions we provided were wrong, this fixes it.
> Correct instructions for changing strimzi's logging level

- operator/src/main/java/org/bf2/operator/managers/ObservabilityManager.java
- operator/src/test/java/org/bf2/operator/managers/ObservabilityManagerTest.java
I'm not sure why we got into the state observed on MGDSTRM-8991 - something removed the owner reference.  When that happens the existing edit/update logic will not add it back.  So this set of modifications makes the logic more consistent with other places.
> MGDSTRM-8991 making sure the observability secret has an owner

- .github/project.yml
[MGDSTRM-9377](https://issues.redhat.com/browse/MGDSTRM-9377)
> Release 0.27.0

- api/src/main/java/org/bf2/operator/ManagedKafkaKeys.java
- api/src/main/java/org/bf2/operator/resources/v1alpha1/ManagedKafka.java
- api/src/main/java/org/bf2/operator/resources/v1alpha1/ManagedKafkaAgent.java
- api/src/test/java/org/bf2/operator/ManagedKafkaKeysTest.java
- operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
- operator/src/main/java/org/bf2/operator/managers/KafkaManager.java
- operator/src/main/java/org/bf2/operator/managers/SecuritySecretManager.java
- operator/src/main/java/org/bf2/operator/managers/StrimziManager.java
- operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
- operator/src/main/java/org/bf2/operator/operands/AdminServer.java
- operator/src/main/java/org/bf2/operator/operands/dev/DevelopmentKafkaCluster.java
- operator/src/test/java/org/bf2/operator/controllers/ManagedKafkaControllerTest.java
- operator/src/test/java/org/bf2/operator/managers/StrimziManagerTest.java
- operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
- sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
- sync/src/main/java/org/bf2/sync/SecretManager.java
- sync/src/test/java/org/bf2/sync/PollerTest.java
- systemtest/src/main/java/org/bf2/systemtest/operator/StrimziOperatorManager.java
Preliminary change for feature to add ability to pause ManagedKafka reconciliation
> [MGDSTRM-9354] Consolidate `managedkafka.bf2.org` label/annotation

- .github/project.yml
> Release 0.28.0

- pom.xml
> Override SnakeYAML to version 1.31

- systemtest/src/test/java/org/bf2/systemtest/integration/UpgradeST.java
This is fix for upgrade test. I see in jenkins that this test does not work because it used plain managedkafka CR instead of call to sync. With this change it works again.
> Fix upgrade test to use sync instead plain ManagedKafka CR

- operator/src/main/java/org/bf2/operator/operands/AbstractCanary.java
@k-wall is to address the canary delete concerns you raised on the delayed deployment pr.  It also removes the blocking scale operation.
> refining canary delete

- operator/src/main/java/org/bf2/operator/managers/IngressControllerManager.java
- operator/src/main/kubernetes/kubernetes.yml
- operator/src/test/java/org/bf2/operator/managers/IngressControllerManagerTest.java
initial commit to force the ingress controller count to be 1  to reduce the costs
> initial commit to force the ingress controller count to be 1 

- perf/scripts/osd-provision.sh
Updating usage info with default instance types for AWS and GCP
> Updating usage message

- operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
- systemtest/src/main/java/org/bf2/systemtest/operator/FleetShardOperatorManager.java
- systemtest/src/main/java/org/bf2/systemtest/operator/StrimziOperatorManager.java
The changes to suspend a Kafka instance modified the `AbstractKafkaCluster#isReconciliationPaused` method to check for the presence of the Strimzi pause reconciliation annotation. Due to the amount of time this annotation is actually present during an upgrade, the `StrimziUpgrading` ready condition reason is set for a much shorter duration, impacting the `UpgradeST`. 
The actual upgrade of the Strimzi version isn't impacted, only the reporting of the ready reason, which is checked by the system test.
This PR also includes a change to the systemtests to align the Subscription label selection criteria more closely with those of the operator and also adds a check for the Strimzi versions in the agent status as a requirement for FSO readiness.
> [MGDSTRM-10315] Restore simple ReconciliationPaused condition check for StrimziUpdating

- operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
- operator/src/test/resources/expected/custom-config-strimzi.yml
- operator/src/test/resources/expected/developer-strimzi.yml
- operator/src/test/resources/expected/strimzi.yml
- operator/src/test/resources/expected/strimzi_su2.yml
Jira: [MGDSTRM-10098](https://issues.redhat.com/browse/MGDSTRM-10098)
> [MGDSTRM-10098] - Removing 9096 listener accessibility from other pods

- pom.xml
Also fixes #803 removal of snakeyaml version overide
> MGDSTRM-9748-Update FSO to Quarkus 2.13

- api/src/main/java/org/bf2/operator/resources/v1alpha1/Versions.java
- api/src/test/java/org/bf2/resources/VersionsTest.java
- common/src/main/java/org/bf2/common/AbstractCustomResourceClient.java
- common/src/main/java/org/bf2/common/OperandUtils.java
- operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaAgentController.java
- operator/src/main/java/org/bf2/operator/controllers/ManagedKafkaController.java
Scaled back what was mentioned on https://issues.redhat.com/browse/MGDSTRM-8648 to keep this just a small set of changes
> Minor clean up of tech debt

- sync/src/main/java/org/bf2/sync/ManagedKafkaSync.java
- sync/src/test/java/org/bf2/sync/PollerTest.java
Allows the control plane to pause syncing to the data plane via the pause annotation https://issues.redhat.com/browse/MGDSTRM-10879
The delete flag is still set to allow for cleanup to proceed.
This usage of the annotation will not intersect with sre usage of the pause annotation, but we can of course use an entirely different annotation key if anyone objects to this reuse.
> MGDSTRM-10879 adding control plane directed pause handling

- operator/src/main/java/org/bf2/operator/managers/OperandOverrideManager.java
- operator/src/main/java/org/bf2/operator/operands/AbstractKafkaCluster.java
- operator/src/test/java/org/bf2/operator/managers/OperandOverrideManagerTest.java
- operator/src/test/java/org/bf2/operator/operands/KafkaClusterTest.java
- operator/src/test/resources/expected/custom-config-strimzi.yml
Use case is to allow the tuning of JWKS cert refresh defaults
> MGDSTRM-10438: allow operator overrides to express listener authentication overrides   
